### ISSUE TITLE
Use new set_rotation(rot) feature to lay down tools on anvil

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/anvil#15]
![](https://cloud.githubusercontent.com/assets/25328789/23722679/9cd502f8-0446-11e7-8b10-22897b03bc2b.png)

Above is now possible (not only mockup-able) with `minetest.set_rotation(rot)`!

**Comment by FaceDeer** [comment]
I've added support for this, falling back to the old behaviour when set_rotation isn't available.
