### ISSUE TITLE
Anvil wear level

### ISSUE THREAD

**Issue by tacotexmex** [minetest-mods/anvil#5]
I'm thinking of ways to reduce the impact the anvil has on gameplay. I looked at MC and they've solved it partly by having the anvil wear out and crack over time, raising the cost of using them in the longer term. How about that?

**Comment by FaceDeer** [comment]
Sounds doable, I can likely add that as a configurable option. Might be a little while before I get to it, though, I've been a bit busy lately and I've got a queue of other modwork that's piled up.

**Comment by tacotexmex** [comment]
Cool. Yes, put this low on the list 😂

**Comment by LoneWolfHT** [comment]
Maybe make the hammers unrepairable and have less health?

**Comment by FaceDeer** [comment]
I've added a setting, "anvil_hammer_is_repairable", that can be used to disable hammer repair. That should prevent infinite reusability of tools without requiring repair materials. It defaults to "true" to preserve existing behaviour.
